### ISSUE TITLE
Compounds with no documentation do not render

### ISSUE THREAD

**Issue by dylanmcreynolds** [als-computing/splash-client#46]
This line of code was meant to warn a user when there is no documentation object coming back from the server, but if there is no documentation object, the reference to documentation blows up the render of the page:

https://github.com/als-computing/splash-client/blob/7161e32780a52505d930131136c6c19905ca58a4/src/views/Compound.vue#L18

**Comment by dylanmcreynolds** [comment]
@thefearlesscoder this is fixed, yes?

**Comment by thefearlesscoder** [comment]
Yes, this has  been fixed.
