### ISSUE TITLE
Change search results to remove columns

### ISSUE THREAD

**Issue by dylanmcreynolds** [als-computing/splash-client#5]
Currently, the splash search page returns a table with columns that are appropriate for experiment results. We need to support finding types of data that include publications, people, institutions and techniques. 

Lets return something that looks more like google where each result has metadata about the result in text below the link.

**Comment by thefearlesscoder** [comment]
I made a pr for this issue https://github.com/als-computing/splash-client/pull/7

**Comment by dylanmcreynolds** [comment]
In GitHub, you can easily link the PR to an issue (https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue), then, when the PR is merged, the issues will be closed automagically.

**Comment by dylanmcreynolds** [comment]
My mistake, @thefearlesscoder  has merely closed an old issue against and old PR. Thanks for doing the bookkeeping!
