### ISSUE TITLE
Make the UI look better for when the client cannot retrieve the gapi library at startup

### ISSUE THREAD

**Issue by J-avery32** [als-computing/splash-client#51]
The client currently just prints a plain text message to the screen when it cannot retrieve the google auth library. There should be a navbar with only the splash logo at the top.

**Comment by dylanmcreynolds** [comment]
I am considering fixing this by remove the whole gapi thing. Rather than a modal window, we can redirect the user to the google page, sending it our redirect ui. This flow is pretty standard OCID/OAuth2, and our code will should with other providers without vendor-specific javascript code.

**Comment by J-avery32** [comment]
I will make this comment a new issue and then close this one, as currently the UI is fixed.
