### ISSUE TITLE
Staging server routing and pasting

### ISSUE THREAD

**Issue by dylanmcreynolds** [als-computing/splash-client#72]
At least with pages, one cannot paste a client link into the browser (https://splash-staging.lbl.gov/pages/e3d507b5-d345-4bf0-b82f-65aed546f0cb and https://splash-staging.lbl.gov/pages) produce NGINX errors.

**Comment by thefearlesscoder** [comment]
Vue recommends using this configuration in nginx.conf

location / {
  try_files $uri $uri/ /index.html;
}


https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations
