### ISSUE TITLE
Integrate my axios requests with nginx scheme

### ISSUE THREAD

**Issue by J-avery32** [als-computing/splash-client#8]
I've noticed that the Vue app appears to have global base url for apis. Which is configured to send to its own url. I am guessing that this is then handled by the nginx setup and forwarded to the flask server. 
However, my code for the search sends a direct request to elasticsearch. I have no idea how I should setup the nginx configuration you intended so we need to discuss how to integrate my search code into this nginx forwarding scheme rather than sending direct requests to elasticsearch. This will require editing of my search code at some later time.

**Comment by thefearlesscoder** [comment]
After looking at the code more I realize that I don't actually understand what's happening at all. Though, it appears that my search code still does not fit into the correct pattern. We need to discuss this soon or at least keep in mind that my search code will need to be fixed at a later date as well as my experiments code which displays a paginated list of all experiments.

**Comment by dylanmcreynolds** [comment]
Would the following url scheme work?
foo.com/              static vue site
foo.com/api         flask
foo.com/search   elastisearch

**Comment by thefearlesscoder** [comment]
Yes, however we need to fix my code and create a script for running nginx with the correct configuration before we implement this.
